language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x mvnw          
script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
  notifications:
    email:
      recipients:
        - hirlawldo413@gmail.com 
